apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeploymentconversao
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
       - name: site
         image: juliasantos/conversao-temperatura2:v1
         ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  selector:
    app: web-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort